### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by alessioalex** [JohnPostlethwait/stringify#31]
```
→ gulp test
[11:14:25] Using gulpfile ~/www/stringify/gulpfile.js
[11:14:25] Starting 'test'...
[11:14:25] Finished 'test' after 22 ms


  the "getExtensions" function
    when passed no options argument
      ✓ should have returned a non-empty array 
      ✓ should have returned the correct extensions 
    when passed an array of file-extensions as an options argument
      ✓ should have returned a non-empty array 
      ✓ should have returned the correct extensions 
    when passed an object with an "extensions" array property as an options argument
      ✓ should have returned a non-empty array 
      ✓ should have returned the correct extensions 

  the "getMinifierOptions" function
    ✓ should have returned default configuration for minifier 
    ✓ should have returned overriden configuration for minifier 

  the "hasStringifiableExtension" function
    when the filename has an extension in the array
      ✓ should have returned "true" 
    when the filename does not have an extension
      ✓ should have returned "false" 

  when the module is required
    ✓ should return a function 
    ✓ should have a method "registerWithRequire" 

  when the module called
    with no options
      ✓ should return a factory function named "browserifyTransform" 
      when the returned function is called with a valid file path
        ✓ should return a Stream object 
    with options as first argument
xxxxxxxxxxxxxxxxxxxxxxxxxxx
      ✓ should return a function named "browserifyTransform" 
      1) should respond to input with the given options
    with a HTML file as first argument
      ✓ should return a Stream object 
      2) should respond to input
    with an unknown file as first argument
      ✓ should return a Stream object 
      ✓ should respond without transformation 

  the "minify" function
    ✓ should return a function 
    ✓ should have default minifier extensions 
    ✓ should minify html content 
    ✓ should not minify html content because minification is not requested 
    ✓ should not minify html content because extension is not supported 

  the "registerWithRequire" function
    ✓ should allow me to require "./file_fixture.txt" as strings 

  the "stringify" function
    ✓ should have returned a string 
    ✓ should begin with module.exports = " 
    ✓ should have perserved newline characters 
    ✓ should have escaped the double-quotes 


  28 passing (20ms)
  2 failing

  1) when the module called with options as first argument should respond to input with the given options:
     TypeError: buf.copy is not a function
      at Function.Buffer.concat (buffer.js:237:9)
      at Stream.end (/home/alessio/www/stringify/src/stringify.js:200:29)
      at _end (/home/alessio/www/stringify/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/alessio/www/stringify/node_modules/through/index.js:74:5)
      at next (/home/alessio/www/stringify/test/main.js:17:12)
      at write (/home/alessio/www/stringify/test/main.js:19:3)
      at Context.<anonymous> (/home/alessio/www/stringify/test/main.js:101:7)
      at callFn (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:373:10)

  2) when the module called with a HTML file as first argument should respond to input:
     TypeError: buf.copy is not a function
      at Function.Buffer.concat (buffer.js:237:9)
      at Stream.end (/home/alessio/www/stringify/src/stringify.js:200:29)
      at _end (/home/alessio/www/stringify/node_modules/through/index.js:65:9)
      at Stream.stream.end (/home/alessio/www/stringify/node_modules/through/index.js:74:5)
      at next (/home/alessio/www/stringify/test/main.js:17:12)
      at write (/home/alessio/www/stringify/test/main.js:19:3)
      at Context.<anonymous> (/home/alessio/www/stringify/test/main.js:135:7)
      at callFn (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/home/alessio/www/stringify/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:373:10)




events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: 2 tests failed.

 alessio: /home/alessio/www/stringify git:master
→ node -v && npm -v
v5.1.1
3.5.3
```

**Comment by Hagendorn** [comment]
I could find out why the unit tests are failing. The problem is that the node API for Buffer.concat() changed between node v0.12 and v4. The "old" Buffer.concat() return the first element from the list when the length is exactly one. This API change has now the effect that these unit tests are failing on line 200 in stringify.js [1].

Here is a link to all API changes:
https://github.com/nodejs/node/wiki/API-changes-between-v0.10-and-v4

And here is the link to the commit which changed the behavior for Buffer.concat():
https://github.com/nodejs/node/commit/f4f16bf03980df4d4366697d40e80da805a38bf8

[1] https://github.com/JohnPostlethwait/stringify/blob/master/src/stringify.js#L200

**Comment by JohnPostlethwait** [comment]
Awesome, thank you! I am working on an updated version of Stringify today that will address this. I will let you know and push to NPM once I have that done.

**Comment by JohnPostlethwait** [comment]
Reproduced this. I have published a new version to NPM with an engine pin to the older versions of Node, and am working on updating this for the newer versions of Node now.

**Comment by JohnPostlethwait** [comment]
I have upgraded to the newer Node stream implementations, and tests are passing again. Thanks for the reports guys. Version 4.0.0 is up on NPM and should fix this.

**Comment by Hagendorn** [comment]
Thanks
