### ISSUE TITLE
lint is not working

### ISSUE THREAD

**Issue by liorwohl** [JohnPostlethwait/stringify#49]
i use this command to build:

browserify -v --no-bundle-external --t eslintify --t browserify-ngannotate --t imgurify --t [ stringify --extensions [.html] --minify --minifier [ --options [ --lint --compress-path --collapseWhitespace --preserveLineBreaks --conservativeCollapse --removeComments --removeAttributeQuotes --removeTagWhitespace ] ] ] --debug --plugin [ minifyify --map app.min.js.map --output app.min.js.map ] app.js --outfile app.min.js

without --lint its working fine but with it its says:

TypeError: lint.testElement is not a function (while stringify was processing C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\components\dashboard\dashboard.html) while parsing file: C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\components\dashboard\dashboard.html
    at Object.HTMLParser.start (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\html-minifier\src\htmlminifier.js:662:16)
    at parseStartTag (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\html-minifier\src\htmlparser.js:384:17)
    at String.replace (native)
    at new global.HTMLParser (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\html-minifier\src\htmlparser.js:239:22)
    at Object.minify (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\html-minifier\src\htmlminifier.js:619:5)
    at minify (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\src\stringify.js:157:27)
    at Stream.transformFn (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\src\stringify.js:219:24)
    at Stream.end (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\browserify-transform-tools\lib\transformTools.js:108:30)
    at _end (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\browserify-transform-tools\node_modules\through\index.js:65:9)
    at Stream.stream.end (C:\SVN\Java\ts\magnus\manager\mgm-web\src\main\webapp\node_modules\stringify\node_modules\browserify-transform-tools\node_modules\through\index.js:74:5)

**Comment by JohnPostlethwait** [comment]
Does it work standalone without being embedded into the browserify options? IE: running stringify by itself.

**Comment by liorwohl** [comment]
how can i run stringify by itself?
